.PHONY: all clean

all: github.svg affiliation.svg email.svg

github.svg:
	wget -nv -O github.svg https://icons.getbootstrap.com/assets/icons/github.svg

affiliation.svg:
	wget -nv -O affiliation.svg https://icons.getbootstrap.com/assets/icons/building.svg

email.svg:
	wget -nv -O email.svg https://icons.getbootstrap.com/assets/icons/envelope.svg

clean:
	$(RM) *.svg
