name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Website
    runs-on: ubuntu-latest
    environment: Kudotoc

    steps:
      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          git clone https://github.com/madman-bob/talks
          make all

      - name: Deploy to host
        env:
          HOST_ADDRESS: ${{ secrets.HOST_ADDRESS }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
          HOST_PATH: ${{ secrets.HOST_PATH }}
          HOST_SSH_FINGERPRINT: ${{ secrets.HOST_SSH_FINGERPRINT }}
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST_SSH_FINGERPRINT" > ~/.ssh/known_hosts
          rsync -a -e "ssh -p $HOST_PORT" _output/ "$HOST_USERNAME@$HOST_ADDRESS:$HOST_PATH"
